export WORKSPACE="$HOME/workspace"
export DOTFILES="$HOME/.dotfiles"
export DEVBOX_NO_PROMPT=true


# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache


# Devbox
export DEVBOX_GLOBAL_PROFILE=$XDG_DATA_HOME/devbox/global/default/.devbox/nix/profile/default
export DEVBOX_GLOBAL_BIN=$DEVBOX_GLOBAL_PROFILE/bin
export DEVBOX_GLOBAL_SHARE=$DEVBOX_GLOBAL_PROFILE/share


# Editor
export EDITOR="nvim"
export VISUAL="nvim"


# Zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file


# Talos OS
export TALOSCONFIG=$XDG_CONFIG_HOME/talos/talosconfig

# Rainfrog
export RAINFROG_CONFIG=$XDG_CONFIG_HOME/rainfrog/config.toml

# Dagger
export DAGGER_NO_NAG=1

# Programming
# Go
export GOPATH="$WORKSPACE/go"
export GOBIN="$WORKSPACE/go/bin"
export GOCACHE="$XDG_CACHE_HOME/go-build"

