# Use Nix build
source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
# WARNING: The Nix install needs to be run before running this script!
source $XDG_CONFIG_HOME/nix-config/activate

# Autocompletions
autoload -U compinit; compinit
source <(devbox completion zsh); compdef _devbox devbox # Devbox
eval "$(zoxide init zsh)"

# Style
eval "$($DEVBOX_GLOBAL_BIN/starship init zsh)"


# Navigation
setopt CORRECT # Try to correct the spelling of commands

source $DEVBOX_PACKAGES_DIR/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $DEVBOX_PACKAGES_DIR/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# Aliases
source $DOTFILES/aliases/aliases
