# Use the global Devbox
eval "$(devbox global shellenv --init-hook)"


# Autocompletions
autoload -U compinit; compinit
source <(devbox completion zsh); compdef _devbox devbox 
eval "$(zoxide init zsh)"
source <(fzf --zsh)


# Style
eval "$($DEVBOX_GLOBAL_BIN/starship init zsh)"


# Navigation
setopt CORRECT # Try to correct the spelling of commands

source $DEVBOX_GLOBAL_SHARE/zsh-autosuggestions/zsh-autosuggestions.zsh
source $DEVBOX_GLOBAL_SHARE/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh


# Aliases
source $DOTFILES/aliases/aliases
