{ pkgs, ... }:

rec {
  username = "oli";
  userFullname = "Oliver Kenyon Wilkins";
  userEmail = "okwilkins@googlemail.com";
  # Generated by: mkpasswd -m scrypt
  initialHashedPassword = "$7$CU..../....Ky0nmU3QG7xuTv8RoBXtu1$4NLnWFNqL0c/4Lzqm9KZCgnrXARLqLU3Glh44m0KDt4";

  networking = import ./networking.nix;

  homeDir = if pkgs.stdenv.isDarwin then "/Users/${username}" else "/home/${username}";
  workspaceDir = "${homeDir}/workspace";
  xdg = rec {
    configDir = ".config";
    dataDir = ".local/share";
    cacheDir = ".cache";
    stateDir = ".local/state";
    configHome = "${homeDir}/${configDir}";
    dataHome = "${homeDir}/${dataDir}";
    cacheHome = "${homeDir}/${cacheDir}";
    stateHome = "${homeDir}/${stateDir}";
  };
  zshDotDir = "${xdg.configHome}/zsh";
}
