{ ... }:

rec {
  username = "oli";
  userFullname = "Oliver Kenyon Wilkins";
  userEmail = "okwilkins@googlemail.com";
  # Generated by: mkpasswd -m scrypt
  initialHashedPassword =
    "$7$CU..../....Ky0nmU3QG7xuTv8RoBXtu1$4NLnWFNqL0c/4Lzqm9KZCgnrXARLqLU3Glh44m0KDt4";

  networking = import ./networking.nix;

  homeDir = "/home/${username}";
  workspaceDir = "${homeDir}/workspace";
  xdg = rec {
    configDir = ".config";
    dataDir = ".local/share";
    cacheDir = ".cache";
    configHome = "${homeDir}/${configDir}";
    dataHome = "${homeDir}/${dataDir}";
    cacheHome = "${homeDir}/${cacheHome}";
  };
  zshDotDir = "${xdg.configHome}/zsh";
}
