{
  lib,
  pkgs,
  config,
  ...
}:

{
  options.system = {
    username = lib.mkOption {
      type = lib.types.str;
      default = "oli";
    };
    userFullname = lib.mkOption {
      type = lib.types.str;
      default = "Oliver Kenyon Wilkins";
    };
    userEmail = lib.mkOption {
      type = lib.types.str;
      default = "okwilkins@googlemail.com";
    };
    homeDir = lib.mkOption {
      type = lib.types.str;
      default =
        if pkgs.stdenv.isDarwin then
          "/Users/${config.system.username}"
        else
          "/home/${config.system.username}";
    };
    workspaceDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.system.homeDir}/workspace";
    };
    initialHashedPassword = lib.mkOption {
      type = lib.types.str;
      # Generated by: mkpasswd -m scrypt
      default = "$7$CU..../....Ky0nmU3QG7xuTv8RoBXtu1$4NLnWFNqL0c/4Lzqm9KZCgnrXARLqLU3Glh44m0KDt4";
    };

    xdg = lib.mkOption {
      type = lib.types.submodule {
        options = {
          configDir = lib.mkOption {
            type = lib.types.str;
            default = ".config";
          };

          dataDir = lib.mkOption {
            type = lib.types.str;
            default = ".local/share";
          };

          cacheDir = lib.mkOption {
            type = lib.types.str;
            default = ".cache";
          };

          stateDir = lib.mkOption {
            type = lib.types.str;
            default = ".local/state";
          };

          configHome = lib.mkOption {
            type = lib.types.str;
            default = "${config.system.homeDir}/${config.system.xdg.configDir}";
          };

          dataHome = lib.mkOption {
            type = lib.types.str;
            default = "${config.system.homeDir}/${config.system.xdg.dataDir}";
          };

          cacheHome = lib.mkOption {
            type = lib.types.str;
            default = "${config.system.homeDir}/${config.system.xdg.cacheDir}";
          };

          stateHome = lib.mkOption {
            type = lib.types.str;
            default = "${config.system.homeDir}/${config.system.xdg.stateDir}";
          };
        };
      };
      default = { };
    };

    zshDotDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.system.xdg.configHome}/zsh";
    };
  };
}
