export WORKSPACE="$HOME/workspace"
export DOTFILES="$HOME/.dotfiles"

# Zsh
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file


# Talos OS
export TALOSCONFIG=$XDG_CONFIG_HOME/talos/talosconfig

# Rainfrog
export RAINFROG_CONFIG=$XDG_CONFIG_HOME/rainfrog/config.toml

# Dagger
export DAGGER_NO_NAG=1

# Programming
# Go
export GOPATH="$WORKSPACE/go"
export GOBIN="$WORKSPACE/go/bin"
export GOCACHE="$XDG_CACHE_HOME/go-build"

