gui:
  # Catppucin blue: https://github.com/catppuccin/lazygit/blob/d3c95a67ea3f778f7705d8ef814f87ac5213436d/themes/mocha/blue.yml
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
authorColors:
  '*': '#b4befe'
  mouseEvents: false
git:
  paging:
    colorArg: always
    pager: delta --paging=never
keybinding:
  universal:
    quit: <esc>
